### ISSUE TITLE
Ranging functions 

### ISSUE THREAD

**Issue by RensWildenbeest** [Lora-net/SWSD003#344]
Hi!

I'm trying to implement a ranging demo using the LR1120, the documentation specifies the existance of a ranging driver but I'm having a hard time finding driver documentation. i have already tried using the SX1280 examples but to no avail. could you point me to the right direction of the documentation if it exist. Alternatively, it would be great if there are code examples available.

**Comment by gbartnik** [comment]
Hello,

As of version 2.2.0 of SWSD003, you will note that term 'Ranging' has been replaced RTToF (Round Trip Time of Flight), per the changelog entry: "Renaming from ranging to RTToF"

RTToF is an advanced function of the transceiver silicon - to learn more about and the potential use-cases, please reach out to us at https://semtech.my.site.com/ldp/ldp_support
