### ISSUE TITLE
[LR1121] SF6 compatibility with SX127x in implicit mode

### ISSUE THREAD

**Issue by JyeSmith** [Lora-net/SWSD003#345]
From the datasheet it is possible to make the LR1121 SF6 compatible with the SX1276 in implicit mode.  So far I have not been successful receiving packets correctly.  The transceiver will trigger the rxdone IRQ, but the packet does not pass a software CRC.

> 1.Set bit 18 of register at address 0xf20414 to 1

Is there any further documentation on what mode the LR1121 must be in before setting the register e.g. STBY, FS, RX mode?  Should the register also be set after writing the SetModulationParams for SF6?

Below is the data I am sending with opcode LR11XX_REGMEM_WRITE_REGMEM32_MASK_OC (0x010C).  Does this look correct?

    wrbuf[0] = 0x00; // MSB
    wrbuf[1] = 0xf2;
    wrbuf[2] = 0x04;
    wrbuf[3] = 0x14;
    // Mask
    wrbuf[4] = 0x00; // MSB
    wrbuf[5] = 0b00000100;
    wrbuf[6] = 0x00;
    wrbuf[7] = 0x00; 
    // Data
    wrbuf[8] = 0x00; // MSB
    wrbuf[9] = 0b00000100;
    wrbuf[10] = 0x00;
    wrbuf[11] = 0x00;

Cheers
Jye

**Comment by nate504** [comment]
Jye, what was your conclusion in trying to get this working?  I'm looking at the same issue.

**Comment by JyeSmith** [comment]
> Jye, what was your conclusion in trying to get this working? I'm looking at the same issue.

I received the below info via email, but since then the user manual has been updated.  You also need to set bit 23 to 0.

![image](https://github.com/user-attachments/assets/62604f5e-19c8-422d-b90c-6ef09e72c969)

**Comment by nate504** [comment]
Thanks for the quick reply.

I'm using LR1120, so slightly different.  I have updated my device's firmware to the latest, and am using the latest LR1120 manual V2.0 (which has the same register changes you pointed out).  I am in SF6 implicit header, but still have no comms b/w SX127x and my LR1120.

Just knowing you got yours working is helpful.  I will keep chugging.

Did you notice if this register change has to be done after all other LoRa parameters are defined?  I could play with the order of operations.

**Comment by JyeSmith** [comment]
I do it after setting the Mod Params.  Below is the how its set.

https://github.com/ExpressLRS/ExpressLRS/blob/f5a745aba833d65c327a8ab7f305f143bb857d39/src/lib/LR1121Driver/LR1121.cpp#L271

**Comment by nate504** [comment]
Yes, I saw that code example, and I'm doing the same.

One difference is that I'm doing the register change after ALL my LoRa settings are defined.  I'll try moving the change to just after Mod Params.  I also see that you are using a V2.1 document, while what's available online is a year older version V2.0.  Maybe there's also newer version for the LR1120 that is not posted yet.

Can you confirm you got yours working?  Thanks for your help.

**Comment by JyeSmith** [comment]
Yep, works fine now.
